import numpy as np
from torch import Tensor

class LDA_Test():
	def __init__(self):

		# Sample input for LDA: 
		self.input_sequences = ['Asbestos scare shuts down mail delivery in Christchurch, New Zealand\n',
                            'U.S. Needs to Play Cards Right in India\n',
                            'How Well Do You Know The Lyrics To Wonka\'s "Pure Imagination"\n',
                            'Sharp Decline in Profit at  Washington Post Co.\n',
                            'Enthralling Playoff Games in an Era of Hard Knocks\n',
                            'Sanctions on Iran: Will Europe Act?\n',
                            'Bravo Pushes Shows  Into Licensing Products\n',
                            '19 Signs You Go To College In A Small Town\n',
                            'What Do You Think Is The Meaning Of Life\n',
                            'The Smell of Success in the Quarter May Change\n']
		
    #Tokenized sentences
		self.output_tokenized = [['asbestos',
                                  'scare',
                                  'shuts',
                                  'down',
                                  'mail',
                                  'delivery',
                                  'in',
                                  'christchurch',
                                  'new',
                                  'zealand'],
                                ['needs', 'to', 'play', 'cards', 'right', 'in', 'india'],
                                ['how',
                                  'well',
                                  'do',
                                  'you',
                                  'know',
                                  'the',
                                  'lyrics',
                                  'to',
                                  'wonka',
                                  'pure',
                                  'imagination'],
                                ['sharp', 'decline', 'in', 'profit', 'at', 'washington', 'post', 'co'],
                                ['enthralling',
                                  'playoff',
                                  'games',
                                  'in',
                                  'an',
                                  'era',
                                  'of',
                                  'hard',
                                  'knocks'],
                                ['sanctions', 'on', 'iran', 'will', 'europe', 'act'],
                                ['bravo', 'pushes', 'shows', 'into', 'licensing', 'products'],
                                ['signs', 'you', 'go', 'to', 'college', 'in', 'small', 'town'],
                                ['what', 'do', 'you', 'think', 'is', 'the', 'meaning', 'of', 'life'],
                                ['the', 'smell', 'of', 'success', 'in', 'the', 'quarter', 'may', 'change']]
		
		self.output_stopword_removal = [['asbestos',
                              'scare',
                              'shuts',
                              'mail',
                              'delivery',
                              'christchurch',
                              'new',
                              'zealand'],
                            ['needs', 'play', 'cards', 'right', 'india'],
                            ['well', 'know', 'lyrics', 'wonka', 'pure', 'imagination'],
                            ['sharp', 'decline', 'profit', 'washington', 'post', 'co'],
                            ['enthralling', 'playoff', 'games', 'era', 'hard', 'knocks'],
                            ['sanctions', 'iran', 'europe', 'act'],
                            ['bravo', 'pushes', 'shows', 'licensing', 'products'],
                            ['signs', 'go', 'college', 'small', 'town'],
                            ['think', 'meaning', 'life'],
                            ['smell', 'success', 'quarter', 'may', 'change']]
		
		self.output_id2word_dictionary = {0: 'asbestos',
                                      1: 'christchurch',
                                      2: 'delivery',
                                      3: 'mail',
                                      4: 'new',
                                      5: 'scare',
                                      6: 'shuts',
                                      7: 'zealand',
                                      8: 'cards',
                                      9: 'india',
                                      10: 'needs',
                                      11: 'play',
                                      12: 'right',
                                      13: 'imagination',
                                      14: 'know',
                                      15: 'lyrics',
                                      16: 'pure',
                                      17: 'well',
                                      18: 'wonka',
                                      19: 'co',
                                      20: 'decline',
                                      21: 'post',
                                      22: 'profit',
                                      23: 'sharp',
                                      24: 'washington',
                                      25: 'enthralling',
                                      26: 'era',
                                      27: 'games',
                                      28: 'hard',
                                      29: 'knocks',
                                      30: 'playoff',
                                      31: 'act',
                                      32: 'europe',
                                      33: 'iran',
                                      34: 'sanctions',
                                      35: 'bravo',
                                      36: 'licensing',
                                      37: 'products',
                                      38: 'pushes',
                                      39: 'shows',
                                      40: 'college',
                                      41: 'go',
                                      42: 'signs',
                                      43: 'small',
                                      44: 'town',
                                      45: 'life',
                                      46: 'meaning',
                                      47: 'think',
                                      48: 'change',
                                      49: 'may',
                                      50: 'quarter',
                                      51: 'smell',
                                      52: 'success'}


		self.output_sample_corpus = [[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)],
                                [(8, 1), (9, 1), (10, 1), (11, 1), (12, 1)],
                                [(13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1)],
                                [(19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1)],
                                [(25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1)],
                                [(31, 1), (32, 1), (33, 1), (34, 1)],
                                [(35, 1), (36, 1), (37, 1), (38, 1), (39, 1)],
                                [(40, 1), (41, 1), (42, 1), (43, 1), (44, 1)],
                                [(45, 1), (46, 1), (47, 1)],
                                [(48, 1), (49, 1), (50, 1), (51, 1), (52, 1)]]
